# Generated by Django 3.1.6 on 2021-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('platform', models.CharField(max_length=255)),
                ('hour', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
