# Generated by Django 3.1.6 on 2021-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
