# Generated by Django 3.1.6 on 2021-10-14 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211014_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hour',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 11, 58, 32, 341926)),
        ),
    ]
