# Generated by Django 3.1.6 on 2021-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211014_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hour',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
