# Generated by Django 3.1.6 on 2021-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211014_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='latency',
            field=models.CharField(default='21', max_length=255),
            preserve_default=False,
        ),
    ]
